import {
  keyValueList,
  filepaths,
  valueList,
} from "@fig/autocomplete-generators";
import { npmScriptsGenerator, dependenciesGenerator } from "./npm";
import { npxSuggestions } from "./npx";
import { createCLIsGenerator } from "./yarn";

// Generated by https://quicktype.io

type Package = {
  name: string;
  version: string;
  description: string;
};

type NpmRegistrySearchResult = {
  objects: {
    package: Package;
  }[];
  [key: string]: any;
};

type NpmsSuggestion = {
  package: Package;
  [key: string]: any;
};
type NpmsSearchResult = {
  total: number;
  results: NpmsSuggestion[] & { highlight: string };
};
type NpmRegistryPkgMeta = {
  "dist-tags": {
    latest: string | Record<string, string>;
    [key: string]: string | Record<string, string>;
  };
  name: string;
  versions: {
    [version: string]: Record<string, any>;
  };
};

type SearchPkgsParams = {
  searchTerm: string;
  scope?: string | undefined;
  keywords?: string[] | undefined;
};
type SearchPkgsProps = (
  props: SearchPkgsParams
) => Promise<NpmsSearchResult | NpmsSuggestion[]>;

const atsInStr = (s: string) => (s.match(/@/g) || []).length;
const npmSearchHandler: (
  /** allows passing keywords from outside this generator context */
  keywords?: string[]
) => Fig.Generator["custom"] =
  (keywords) =>
  async (
    _tokens,
    executeShellCommand,
    generatorContext
  ): Promise<Fig.Suggestion[]> => {
    const { searchTerm } = generatorContext;
    if (!searchTerm) {
      return [];
    }

    const getPackages: SearchPkgsProps = async ({
      searchTerm,
      scope,
      keywords,
    }) => {
      if (!searchTerm) {
        return [];
      }
      const NPMS_BASE_URL = "https://api.npms.io/v2/search";
      const searchParams = {
        q: searchTerm,
        size: "20",
      };

      console.log(`initial searchTerm: ${searchTerm}`);

      // keywords can only be used on the /search endpoint
      if (keywords?.length > 0 || !!scope) {
        // Add optional keyword parameter
        const keywordParameter =
          keywords?.length > 0 ? `+keywords:${keywords.join(",")}` : "";
        const scopeParameter = scope ? `+scope:${scope}` : "";

        searchParams["q"] = `${searchTerm}${keywordParameter}${scopeParameter}`;

        // scope can only be used on the /search endpoint
        // remove the suggestions endpoint
        const searchUrl =
          NPMS_BASE_URL +
          "?" +
          Object.keys(searchParams)
            .map((key) => `${key}=${searchParams[key]}`)
            .join("&");

        const queryPackagesCmd = `curl -s -H "Accept: application/json" "${searchUrl}"`;
        console.log(`queryPackagesCmd: /search: ${queryPackagesCmd}`);
        const result = await executeShellCommand(queryPackagesCmd);
        return JSON.parse(result) as NpmsSearchResult;
      }

      const suggestionUrl =
        NPMS_BASE_URL +
        "/suggestions" +
        "?" +
        `${Object.keys(searchParams)
          .map((key) => `${key}=${searchParams[key]}`)
          .join("&")}`;

      const queryPackagesCmd = `curl -s -H "Accept: application/json" "${suggestionUrl}"`;
      console.log(`queryPackagesCmd suggestions: ${queryPackagesCmd}`);
      const result = await executeShellCommand(queryPackagesCmd);

      return JSON.parse(result) as NpmsSuggestion[];
    };

    const getPkgVersions: (
      searchTerm: string
    ) => Promise<NpmRegistryPkgMeta> = async (searchTerm) => {
      // Remove the last character from the search term, which is the version
      searchTerm = searchTerm.slice(0, -1);
      const queryVersions = `curl -s -H "Accept: application/vnd.npm.install-v1+json" https://registry.npmjs.org/${searchTerm}`;
      return JSON.parse(await executeShellCommand(queryVersions));
    };

    // Regex to match npm package names with optional scope and version
    const searchTermRegex =
      /^(?:@(?<scope>[\w-]+)\/)?(?<searchTerm>@?[\w-\/]+)(?:@(?<version>.*))?/g;
    const searchTermMatcher = searchTermRegex.exec(
      searchTerm
    ) as SearchTermMatcher;

    console.log({ searchTermMatcher });

    type SearchTermMatcher =
      | (RegExpExecArray & {
          groups?: {
            scope: string | undefined;
            searchTerm: string;
            version: string | undefined;
          };
        })
      | null;

    try {
      const termMatches = searchTermMatcher?.groups;

      console.log("regex groups: ", termMatches);

      // If there is a version, only return version results from npm registry endpoint.
      if (termMatches && termMatches.version) {
        const data = await getPkgVersions(termMatches.searchTerm);
        // create dist tags suggestions
        const versions = Object.entries(data["dist-tags"] || {}).map(
          ([key, value]) => ({
            name: key,
            description: value,
          })
        ) as Fig.Suggestion[];
        // create versions
        versions.push(
          ...Object.keys(data.versions)
            .map((version) => ({ name: version }) as Fig.Suggestion)
            .reverse()
        );
        return versions;
      }

      const results = await getPackages({
        keywords,
        ...termMatches,
      });

      const suggestions = Array.isArray(results) ? results : results.results;

      return suggestions.map(
        (item) =>
          ({
            name: item.package.name,
            description: item.package.description,
          }) as Fig.Suggestion
      );
    } catch (error) {
      console.error(error);
      return [];
    }
  };

// GENERATORS
const searchNpmGenerator: (tokens?: string[]) => Fig.Generator = (tokens) => {
  return {
    trigger: (newToken, oldToken) => {
      console.log("oldToken: " + oldToken, "newToken: " + newToken);
      // If the package name starts with '@', we want to trigger when
      // the 2nd '@' is typed because we'll need to generate version
      // suggetsions
      // e.g. @typescript-eslint/types
      if (oldToken.startsWith("@")) {
        return !(atsInStr(oldToken) > 1 && atsInStr(newToken) > 1);
      }

      // If the package name doesn't start with '@', then trigger when
      // we see the first '@' so we can generate version suggestions
      return !(oldToken.includes("@") && newToken.includes("@"));
    },
    getQueryTerm: (t) => {
      if (atsInStr(t) > 1) {
        return t.split("@")[1];
      }
      return t;
    },
    //   cache: {
    //     ttl: 1000 * 60 * 60 * 24 * 2, // 2 days
    //   },
    custom: npmSearchHandler(),
  };

/**
 * Similar to the npm dependency generator, but points to different global directory
 */
const bunDependencyGenerator: Fig.Generator = {
  trigger: (newToken) => newToken === "-g" || newToken === "--global",
  custom: async function (tokens, executeShellCommand) {
    const isGlobal = tokens.some((t) => t === "-g" || t === "--global");

    const packageParser = (packageContent: Record<string, any>) => {
      const dependencies = packageContent["dependencies"] ?? {};
      const devDependencies = packageContent["devDependencies"];
      const optionalDependencies = packageContent["optionalDependencies"] ?? {};
      Object.assign(dependencies, devDependencies, optionalDependencies);
      return Object.keys(dependencies)
        .filter((pkgName) => {
          const isListed = tokens.some((current) => current === pkgName);
          return !isListed;
        })
        .map((pkgName) => ({
          name: pkgName,
          icon: "📦",
          description: dependencies[pkgName]
            ? "dependency"
            : optionalDependencies[pkgName]
            ? "optionalDependency"
            : "devDependency",
        }));
    };

    if (isGlobal) {
      const out = await executeShellCommand(
        "cat $BUN_INSTALL/install/global/package.json"
      );
      const packageContent = JSON.parse(out);
      return packageParser(packageContent).map((pkg) => ({
        ...pkg,
        description: pkg.description + " (global)",
      })) as Fig.Suggestion[];
    } else {
      const out = await executeShellCommand("cat $(npm prefix)/package.json");
      const packageContent = JSON.parse(out);
      return packageParser(packageContent);
    }
  },
};

const icon = "https://bun.sh/logo.svg";

/** Suggest common ports for the various --inspect options */
const inspectArgs: Fig.SingleOrArray<Fig.Arg> = {
  name: "[host:]port",
  isOptional: true,
  suggestions: [
    {
      name: "3000",
      icon: "fig://icon?type=box",
      description: "Serve on port 3000",
    },
    {
      name: "8080",
      icon: "fig://icon?type=box",
      description: "Serve on port 8080",
    },
  ],
  description: "Activate inspector on particular port and/or hostname",
};

const loaders = [
  "js",
  "jsx",
  "ts",
  "tsx",
  "json",
  "toml",
  "text",
  "file",
  "wasm",
  "napi",
];
/** Format from https://github.com/oven-sh/bun/blob/dcbcf9803a19be989c0f48d22a50a43731fcfacd/src/cli.zig */
const sharedPublicParams: Fig.Option[] = [
  {
    name: ["-h", "--help"],
    description: "Display this help and exit",
  },
  {
    name: ["-b", "--bun"],
    description:
      "Force a script or package to use Bun's runtime instead of Node.js (via symlinking node)",
  },
  {
    name: "--cwd",
    args: {
      name: "path",
      description:
        "Absolute path to resolve files & entry points from. This just changes the process' cwd",
    },
  },
  {
    name: ["-c", "--config"],
    args: {
      name: "path",
      template: "filepaths",
      description: "Config file to load Bun from (e.g. -c bunfig.toml)",
      isOptional: true,
    },
    description: "Load config (bunfig.toml)",
  },
  {
    name: "--extension-order",
    args: {
      name: "order",
      isVariadic: true,
      description: "Defaults to: .tsx,.ts,.jsx,.js,.json",
    },
  },
  {
    name: "--jsx-factory",
    args: {
      name: "name",
      suggestions: ["React.createElement", "h", "preact.h"],
    },
    description: `Changes the function called when compiling JSX elements using the classic JSX runtime`,
  },
  {
    name: "--jsx-fragment",
    priority: 49,
    args: { name: "string", isOptional: true },
    insertValue: "--jsx-fragment='{cursor}'",
    description: "Changes the function called when compiling JSX fragments",
  },
  {
    name: "--jsx-import-source",
    args: { name: "module", suggestions: ["react"] },
    description: `Declares the module specifier to be used for importing the jsx and jsxs factory functions. Default: "react"`,
  },
  {
    name: "--jsx-runtime",
    args: { name: "name", suggestions: ["automatic", "classic"] },
    description: `"automatic" (default) or "classic"`,
  },
  {
    name: ["-r", "--preload"],
    args: {
      name: "args",
      isVariadic: true,
      description: "Import a module before other modules are loaded",
    },
  },
  {
    name: "--main-fields",
    args: {
      name: "args",
      isVariadic: true,
      description:
        "Main fields to lookup in package.json. Defaults to --target dependent",
    },
  },
  {
    name: "--no-summary",
    description: "Don't print a summary (when generating .bun)",
  },
  {
    name: ["-v", "--version"],
    description: "Print version and exit",
  },
  {
    name: "--revision",
    description: "Print version with revision and exit",
  },
  {
    name: "--tsconfig-override",
    args: {
      name: "overrides",
      description: "Load tsconfig from path instead of cwd/tsconfig.json",
    },
  },
  {
    name: ["-d", "--define"],
    args: {
      name: "k=v",
      isVariadic: true,
      description:
        "Substitute key=value while parsing, e.g. --define process.env.NODE_ENV=development",
    },
  },
  {
    name: ["-e", "--external"],
    args: {
      name: "args",
      isVariadic: true,
      description:
        "Exclude module from transpilation (can use * wildcards). ex: -e react",
    },
  },
  {
    name: ["-l", "--loader"],
    args: {
      name: "args",
      isVariadic: true,
      description:
        "Parse files with .ext:loader, e.g. --loader .js:jsx. Valid loaders: js, jsx, ts, tsx, json, toml, text, file, wasm, napi",
      generators: keyValueList({
        keys: loaders.map((loader) => "." + loader),
        values: loaders,
      }),
    },
  },
  {
    name: ["-u", "--origin"],
    args: {
      name: "args",
      description: 'Rewrite import URLs to start with --origin. Default: ""',
    },
  },
  {
    name: ["-p", "--port"],
    args: {
      name: "args",
      description: 'Port to serve Bun\'s dev server on. Default: "3000"',
    },
  },
  {
    name: "--smol",
    description: "Use less memory, but run garbage collection more often",
  },
  {
    name: "--minify",
    description: "Minify (experimental)",
    priority: 50,
  },
  {
    name: "--minify-syntax",
    description: "Minify syntax and inline data (experimental)",
  },
  {
    name: "--minify-whitespace",
    description: "Minify whitespace (experimental)",
  },
  {
    name: "--minify-identifiers",
    description: "Minify identifiers",
  },
  {
    name: "--no-macros",
    description:
      "Disable macros from being executed in the bundler, transpiler and runtime",
  },
  {
    name: "--target",
    description: "Target environment",
    priority: 50,
    args: {
      generators: valueList({
        values: ["node", "browser", "bun"],
      }),
    },
  },
  {
    name: "--inspect",
    description: "Activate Bun's debugger for a file",
    requiresSeparator: true,
    args: inspectArgs,
  },
  {
    name: "--inspect-wait",
    description:
      "Activate Bun's Debugger, wait for a connection before executing",
    requiresSeparator: true,
    args: inspectArgs,
  },
  {
    name: "--inspect-brk",
    description:
      "Activate Bun's Debugger, set breakpoint on first line of code and wait",
    requiresSeparator: true,
    args: inspectArgs,
  },
  {
    name: "--if-present",
    description: "Exit if the entrypoint does not exist",
  },
];

// note: we are keeping --port and --origin as it can be reused for bun build and elsewhere
const notBunDevFlags: Fig.Option[] = [
  {
    name: "--hot",
    description:
      "Enable auto reload in the Bun runtime, test runner, or bundler",
    priority: 50,
  },
  {
    name: "--watch",
    description: "Automatically restart the process on file change",
    priority: 50,
  },
  {
    name: "--no-install",
    description: "Disable auto install in the Bun runtime",
  },
  {
    name: "-i",
    description:
      "Automatically install dependencies and use global cache in Bun's runtime, equivalent to --install=fallback",
  },
  {
    name: "--install",
    args: {
      name: "arg",
      description: `Install dependencies automatically when no node_modules are present, default: "auto". "force" to ignore node_modules, fallback to install any missing`,
      suggestions: ["auto", "force", "fallback", "disable"],
    },
  },
  {
    name: "--prefer-offline",
    description:
      "Skip staleness checks for packages in the Bun runtime and resolve from disk",
  },
  {
    name: "--prefer-latest",
    description:
      "Use the latest matching versions of packages in the Bun runtime, always checking npm",
  },
  {
    name: "--silent",
    description: "Don't repeat the command for bun run",
  },
];

const buildOnlyParams: Fig.Option[] = [
  {
    name: "compile",
    description:
      "Generate a standalone Bun executable containing your bundled code",
    priority: 50,
  },
  {
    name: "--format",
    description:
      "Specifies the module format to build to. Only esm is supported currently",
    args: {
      name: "args",
      suggestions: ["esm"],
    },
  },
  {
    name: "--outdir",
    description: 'Default to "dist" if multiple files',
    priority: 50,
    args: {
      name: "path",
    },
  },
  {
    name: "--outfile",
    description: "Write to a file",
    priority: 50,
    args: {
      name: "path",
    },
  },
  {
    name: "--root",
    description: "Root directory used for multiple entry points",
    args: {
      name: "path",
    },
  },
  {
    name: "--splitting",
    description: "Enable code splitting",
    priority: 50,
  },
  {
    name: "--public-path",
    description: "A prefix to be appended to any import paths in bundled code",
    args: {
      name: "args",
    },
  },
  {
    name: "--sourcemap",
    description: "Build with sourcemaps - 'inline', 'external', or 'none'",
    requiresSeparator: "-",
    priority: 50,
    args: {
      name: "args",
      isOptional: true,
      suggestions: ["inline", "external", "none"],
    },
  },
  {
    name: "--entry-naming",
    description:
      'Customize entry point filenames. Defaults to "[dir]/[name].[ext]"',
    args: {
      name: "args",
    },
  },
  {
    name: "--chunk-naming",
    description: 'Customize chunk filenames. Defaults to "[name]-[hash].[ext]"',
    args: {
      name: "args",
    },
  },
  {
    name: "--asset-naming",
    description: 'Customize asset filenames. Defaults to "[name]-[hash].[ext]"',
    args: {
      name: "args",
    },
  },
  {
    name: "--server-components",
    description: "Enable React Server Components (experimental)",
  },
  {
    name: "--no-bundle",
    description: "Transpile file only, do not bundle",
  },
];

const testOnlyParams: Fig.Option[] = [
  {
    name: "--timeout",
    description: "Set the per-test timeout in milliseconds, default is 5000",
    args: {
      name: "number",
    },
  },
  {
    name: "--update-snapshots",
    description: "Update snapshot files",
  },
  {
    name: "--rerun-each",
    description:
      "Re-run each test file <NUMBER> times, helps catch certain bugs",
    args: {
      name: "number",
    },
  },
  {
    name: "--only",
    description: 'Only run tests that are marked with "test.only()"',
  },
  {
    name: "--todo",
    description: 'Include tests that are marked with "test.todo()"',
  },
  {
    name: "--coverage",
    description: "Generate a coverage profile",
  },
  {
    name: "--bail",
    description:
      "Exit the test suite after <NUMBER> failures. If you do not specify a number, it defaults to 1",
    args: {
      name: "number",
      isOptional: true,
    },
  },
  {
    name: ["-t", "--test-name-pattern"],
    description: "Run only tests with a name that matches the given regex",
    args: {
      name: "pattern",
    },
  },
];

const debugParams: Fig.Option[] = [
  {
    name: "--dump-environment-variables",
    description:
      "Dump environment variables from .env and process as JSON and quit. Useful for debugging",
    priority: 49,
  },
  {
    name: "--dump-limits",
    description: "Dump system limits. Useful for debugging",
    priority: 49,
  },
];

const publicParams = [...sharedPublicParams, ...notBunDevFlags];
const buildParams = [...publicParams, ...buildOnlyParams, ...debugParams];
const testParams = [...publicParams, ...testOnlyParams, ...debugParams];

const dependencyOptions: Fig.Option[] = [
  {
    name: ["-c", "--config"],
    args: {
      name: "path",
      template: "filepaths",
      isOptional: true,
    },
    description: "Load config (bunfig.toml)",
  },
  {
    name: ["-y", "--yarn"],
    description: "Write a yarn.lock file (yarn v1)",
  },
  {
    name: ["-p", "--production"],
    description: "Don't install devDependencies",
  },
  {
    name: "--no-save",
    description: "Don't save a lockfile",
  },
  {
    name: "--save",
    description: "Save to package.json",
  },
  {
    name: "--dry-run",
    description: "Don't install anything",
  },
  {
    name: "--frozen-lockfile",
    description: "Disallow changes to lockfile",
  },
  {
    name: ["-f", "--force"],
    description:
      "Always request the latest versions from the registry & reinstall all dependencies",
  },
  {
    name: "--cache-dir",
    args: { name: "path", template: "folders" },
    description: "Store & load cached data from a specific directory path",
  },
  {
    name: "--no-cache",
    description: "Ignore manifest cache entirely",
  },
  {
    name: "--silent",
    description: "Don't log anything",
  },
  {
    name: "--verbose",
    description: "Excessively verbose logging",
  },
  {
    name: ["-g", "--global"],
    description: "Install globally",
  },
  {
    name: "--cwd",
    args: { name: "path", template: "folders" },
    description: "Set a specific cwd",
  },
  {
    name: "--backend",
    args: {
      name: "syscall",
      suggestions: [
        {
          name: "hardlink",
          description: "Default on Linux.",
        },
        {
          name: "clonefile",
          description: "Default on macOS.",
        },
        {
          name: "clonefile_each_dir",
          description:
            "Similar to clonefile, except it clones each file individually per directory. It is only available on macOS and tends to perform slower than clonefile.",
        },
        {
          name: "copyfile",
          description:
            "The fallback used when any of the above fail. It is the slowest option. On macOS, it uses fcopyfile(); on Linux it uses copy_file_range().",
        },
        {
          name: "symlink",
          description:
            "Currently used only for file: (and eventually link:) dependencies. To prevent infinite loops, it skips symlinking the node_modules folder.",
        },
      ],
    },
    description:
      "Platform-specific optimizations for installing dependencies. For macOS, 'clonefile' (default), 'copyfile'",
  },
  {
    name: "--link-native-bins",
    args: {
      name: "args",
      isVariadic: true,
    },
    description:
      "Link 'bin' from a matching platform-specific 'optionalDependencies' instead. Default: esbuild, turbo",
  },
  {
    name: "--help",
    description: "Print the help menu",
  },
  {
    name: "--no-progress",
    description: "Disable the progress bar",
  },
  {
    name: "--no-summary",
    description: "Don't print a summary",
  },
  {
    name: "--no-verify",
    description: "Skip verifying integrity of newly downloaded packages",
  },
  {
    name: "--ignore-scripts",
    description:
      "Skip lifecycle scripts in the project's package.json (dependency scripts are never run)",
  },
  {
    name: ["-d", "--dev", "-D", "--development"],
    description: "Install as devDependency",
    priority: 75,
    isRepeatable: false,
  },
  {
    name: "--exact",
    description: "Install exact version",
  },
  {
    name: "--optional",
    description: "Install as optionalDependency",
  },
];

/** Generate the globally linked packages stored in $BUN_INSTALL directory */
const bunLinksGenerator: Fig.Generator = {
  script:
    "command find $BUN_INSTALL/install/global/node_modules -type l | awk -F 'node_modules/' '{print $2}'",
  postProcess(out) {
    return out.split("\n").map((dep) => {
      return {
        name: dep,
        description:
          "Create a symlink from this pacakage in the global registry to the current project",
        icon: "📦",
      };
    });
  },
  cache: {
    strategy: "stale-while-revalidate",
    ttl: 60 * 60 * 24 * 3 * 1000, // 3 days
  },
};

const spec: Fig.Spec = {
  name: "bun",
  description:
    "A fast bundler, transpiler, JavaScript Runtime and package manager for web software",
  icon,
  args: [
    {
      name: "file",
      generators: [
        // js jsx mjs cjs ts tsx mts cts
        filepaths({ matches: /\.[mc]?[jt]sx?$/ }),
        npmScriptsGenerator,
      ],
    },
    {
      name: "args",
    },
  ],
  // These flags are used before the subcommand or file
  options: publicParams.filter(
    (param) =>
      param.name.includes("--inspect") ||
      param.name.includes("--hot") ||
      param.name.includes("--watch")
  ),
  subcommands: [
    {
      name: ["c", "create"],
      icon,
      description: "Start a new project from a template",
      args: [
        {
          name: "template",
          description: "Package from @bun-examples, GitHub repo, or local file",
          suggestions: [
            "react",
            "next",
            "hono",
            "discord-interactions",
            "blank",
            "bun-bakery",
            ...npxSuggestions
              .filter((bin) =>
                typeof bin.name === "string"
                  ? bin.name.startsWith("create-")
                  : bin.name.some((name) => name.startsWith("create-"))
              )
              .map((bin) => {
                let name = bin.name;
                if (typeof name !== "string") name = name[0];
                name = name.replace(/^create-/, "");

                return { ...bin, name, priority: 76 };
              }),
          ],
          generators: [
            { template: "folders" },
            { script: "command ls -1 ~/.bun-create", splitOn: "\n" },
            { script: "command ls -1 .bun-create", splitOn: "\n" },
            createCLIsGenerator,
          ],
          loadSpec: async (token) => ({
            name: "create-" + token,
            type: "global",
          }),
          isCommand: true,
        },
        {
          name: "name",
          template: "folders",
          suggestCurrentToken: true,
        },
      ],
      options: [
        { name: "--force", description: "Overwrite existing files" },
        { name: "--no-install", description: "Don't install node_modules" },
        { name: "--no-git", description: "Don't create a git repository" },
        { name: "--verbose", description: "Too many logs" },
        {
          name: "--no-package-json",
          description: "Disable package.json transforms",
        },
        {
          name: "--open",
          description: "On finish, start bun and open in browser",
        },
      ],
    },
    {
      name: "run",
      icon,
      description: "Run a package.json script or executable",
      args: {
        name: "script",
        filterStrategy: "fuzzy",
        generators: [
          filepaths({
            extensions: ["ts", "tsx", "js", "jsx", "mjs", "cjs"],
          }),
          npmScriptsGenerator,
        ],
      },
    },
    {
      name: ["i", "install"],
      icon: "📦",
      description: "Install dependencies for a package.json",
      options: dependencyOptions,
    },
    {
      name: ["a", "add"],
      icon: "📦",
      description: "Add a dependency to package.json",
      options: dependencyOptions,
      args: {
        name: "package",
        isVariadic: true,
        debounce: true,
        generators: searchNpmGenerator(),
        filterStrategy: "fuzzy",
      },
    },
    {
      name: ["rm", "remove"],
      icon: "📦",
      description: "Remove a dependency from package.json",
      options: dependencyOptions,
      args: {
        name: "package",
        filterStrategy: "fuzzy",
        generators: bunDependencyGenerator,
        isVariadic: true,
      },
    },
    {
      name: ["build", "bun"],
      icon,
      description: "Bundle files using Bun's native bundler",
      args: {
        name: "entrypoints",
        isVariadic: true,
        generators: filepaths({
          extensions: ["ts", "tsx", "js", "jsx", "mjs", "cjs"],
        }),
        description:
          "Entrypoint to bundle. If multiple entrypoints provided, must specify --outdir",
      },
      options: buildParams,
    },
    {
      name: "update",
      icon,
      description: "Update outdated dependencies",
      options: dependencyOptions,
      args: {
        name: "package",
        filterStrategy: "fuzzy",
        isOptional: true,
        generators: bunDependencyGenerator,
        isVariadic: true,
      },
    },
    {
      name: "link",
      icon: "📦",
      description:
        "Run without an argument to register this package to the global package registry. Uses the name field from package.json",
      args: {
        name: "package",
        filterStrategy: "fuzzy",
        isOptional: true,
        generators: bunLinksGenerator,
        description: "Install a package from the global package registry",
      },
      options: [
        {
          name: "--save",
          description: "Save to package.json",
          dependsOn: ["package"],
        },
      ],
    },
    {
      name: "unlink",
      icon: "📦",
      description: "Unlink this package from the global package registry",
      // Unliking a package by name is not yet implemented. Use bunLinksGenerator once it is implemented.
    },
    {
      name: "upgrade",
      icon,
      description: "Get the latest version of bun",
      options: [
        {
          name: "--canary",
          description: "Install the latest canary release",
        },
      ],
    },
    {
      name: "test",
      icon,
      description: "Run unit tests with Bun",
      args: {
        name: "files",
        generators: {
          // Suggest test files -> https://bun.sh/docs/cli/test. (not in node_modules or .git)
          script:
            'command find $(npm prefix) | grep -E ".*.(test|_test|spec|_spec).(ts|tsx|js|jsx)$" | grep -vE ".*/node_modules/.*" | sed "s|$(npm prefix)/||"',
          postProcess(out) {
            return out.split("\n").map((file) => {
              return {
                name: file.split("/").pop(),
                priority: 76,
                description: `run ${file}`,
                insertValue: file,
              };
            });
          },
          cache: {
            strategy: "stale-while-revalidate",
            ttl: 60 * 60 * 1000, // 1 hour
          },
        },
        isVariadic: true,
        filterStrategy: "fuzzy",
        isOptional: true,
        description: "Test files to run",
      },
      options: testParams,
    },
    {
      name: "pm",
      icon,
      description: "Set of utilities for working with Bun's package manager",
      subcommands: [
        {
          name: "bin",
          description: "Print the path to bin folder",
          options: [
            {
              name: ["-g", "--global"],
              description: "Print the path to the global bin folder",
            },
          ],
        },
        {
          name: "cache",
          description: "Print the path to the cache folder",
          subcommands: [
            {
              name: "rm",
              description: "Clear Bun's global module cache",
            },
          ],
        },
        {
          name: "hash",
          description: "Generate & print the hash of the current lockfile",
        },
        {
          name: "hash-print",
          description: "Print the hash stored in the current lockfile",
        },
        {
          name: "hash-string",
          description: "Print the string used to hash the lockfile",
        },
        {
          name: "ls",
          description:
            "List the dependency tree according to the current lockfile",
          options: [
            {
              name: "--all",
              description:
                "To print all installed dependencies, including nth-order dependencies",
            },
            {
              name: ["-g", "--global"],
              description: "List the global dependency tree",
            },
          ],
        },
      ],
    },
    {
      name: "completions",
      icon,
      description: "Install shell completions",
    },
    {
      name: "discord",
      icon: "fig://icon?type=discord",
      description: "Open bun's Discord server",
    },
    {
      name: "help",
      description: "Print the help menu",
      icon,
    },
    {
      name: "x",
      icon,
      description: "Run an npx command",
      loadSpec: "bunx",
    },
    {
      name: "repl",
      icon,
      description:
        "Run a REPL (read eval print loop) with the Bun runtime.(experimental)",
    },
    {
      name: "init",
      icon,
      description: "Initialize a new bun project",
      options: [
        {
          name: ["-y", "--yes"],
          description: "Answer yes to all prompts",
        },
      ],
    },
  ],
};

export default spec;
